# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "862a81c13ddf8d91720c091d700de88d"
name = "AI Smart Upsell Pro"
application_url = "https://shopifyfrontend.bcstdr.site/"
embedded = true
handle = "ai-smart-upsell-pro"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  uri = "https://shopifybackend.bcstdr.site/webhooks/gdpr/customer-erasure"
  compliance_topics = [ "customers/redact" ]

  [[webhooks.subscriptions]]
  uri = "https://shopifybackend.bcstdr.site/webhooks/gdpr/customer-request"
  compliance_topics = [ "customers/data_request" ]

  [[webhooks.subscriptions]]
  uri = "https://shopifybackend.bcstdr.site/webhooks/gdpr/shop-erasure"
  compliance_topics = [ "shop/redact" ]

[auth]
redirect_urls = [ "https://shopifybackend.bcstdr.site/shopify/callback" ]

[pos]
embedded = false
